#!/usr/bin/env bash
# displays numbers from 1 to 100.

cont=1
while [ $cont -lt 101 ]
do
    if [ $((cont%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((cont%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((cont%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$cont"
    fi
    ((cont+=1))
done
